# Generated by Django 2.2.3 on 2019-07-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description_text', models.TextField()),
                ('number_of_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netting_youth.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description_text', models.TextField()),
                ('deadline', models.DateField()),
                ('related_tasklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netting_youth.TaskList')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('surname', models.CharField(max_length=1024, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=1024, null=True)),
                ('country', models.CharField(max_length=1024, null=True)),
                ('related_facebook', models.CharField(max_length=1024, null=True)),
                ('type_of_membership', models.CharField(choices=[('ngo', 'Non-Governmental Organization'), ('youngster', 'Youngster'), ('company', 'Private Sector'), ('public_sector', 'Public Sector')], max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='related_tasklist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netting_youth.TaskList'),
        ),
        migrations.AddField(
            model_name='problem',
            name='related_thematic_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netting_youth.ThematicArea'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=1024)),
                ('description_text', models.TextField()),
                ('related_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netting_youth.Problem')),
            ],
        ),
    ]
